all: \
	iso/movie/ughCutscene.str \
	iso/movie/gunsCutscene.str \
	iso/movie/stressCutscene.str \

# STR converts
iso/movie/%.str: iso/movie/%.mp4
	tools/psxavenc/psxavenc -t str2 -r 15 -I -b 4 -c 2 -x 2 $< $@
